In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [4]:
print("First few elements of X_train:\n", X_train[:5])
print("Type of X_train:",type(X_train))

First few elements of X_train:
 [[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]]
Type of X_train: <class 'numpy.ndarray'>


In [5]:
print("First few elements of y_train:", y_train[:5])
print("Type of y_train:",type(y_train))

First few elements of y_train: [1 1 0 0 1]
Type of y_train: <class 'numpy.ndarray'>


In [6]:
print ('The shape of X_train is:', X_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(X_train))

The shape of X_train is: (10, 3)
The shape of y_train is:  (10,)
Number of training examples (m): 10


In [13]:
def compute_entropy(y):
    if(len(y)==0):
        return 0
    else:
        p_1 = np.sum(np.equal(y,1))/len(y)
        if p_1 !=0 and p_1!=1:
            entropy  = -p_1*np.log2(p_1) - (1-p_1)*np.log2(1-p_1)
            return entropy
        else:
            return 0

In [15]:
print("Entropy at root node: ", compute_entropy(y_train)) 

Entropy at root node:  1.0


In [19]:
def split_dataset(X, node_indices, feature):
    left_indices = []
    right_indices = []
    for i in node_indices:
        if X[i,feature] ==1:
            left_indices.append(i)
        else:
            right_indices.append(i)
    return left_indices, right_indices

In [22]:
root_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
feature = 0

left_indices, right_indices = split_dataset(X_train, root_indices, feature)

print("Left indices: ", left_indices)
print("Right indices: ", right_indices)

Left indices:  [0, 1, 2, 3, 4, 7, 9]
Right indices:  [5, 6, 8]


In [31]:
def compute_information_gain(X, y, node_indices, feature):
    left_indices ,right_indices = split_dataset(X, node_indices, feature)
    h_left = compute_entropy(y[left_indices])
    h_right = compute_entropy(y[right_indices])
    node_ent = compute_entropy(y[node_indices])
    w_left = len(left_indices)/len(node_indices)
    w_right = len(right_indices)/len(node_indices)
    info_gain = node_ent - w_left* h_left - w_right*h_right
    return info_gain

In [37]:
info_gain0 = compute_information_gain(X_train, y_train, root_indices, feature=0)
print("Information Gain from splitting the root on brown cap: ", info_gain0)
    
info_gain1 = compute_information_gain(X_train, y_train, root_indices, feature=1)
print("Information Gain from splitting the root on tapering stalk shape: ", info_gain1)

info_gain2 = compute_information_gain(X_train, y_train, root_indices, feature=2)
print("Information Gain from splitting the root on solitary: ", info_gain2)

Information Gain from splitting the root on brown cap:  0.03485155455967709
Information Gain from splitting the root on tapering stalk shape:  0.12451124978365324
Information Gain from splitting the root on solitary:  0.2780719051126377


In [54]:
def get_best_split(X, y, node_indices): 
    max_info_feature = 0
    max_info_gain = 0
    for feature in range(X.shape[1]):
        curr_gain = compute_information_gain(X,y,node_indices, feature)
        if curr_gain > max_info_gain:
            max_info_feature = feature
            max_info_gain = curr_gain 
    return max_info_feature

In [56]:
best_feature = get_best_split(X_train, y_train, root_indices)
print("Best feature to split on: %d" % best_feature)

Best feature to split on: 2


In [100]:
tree = []

def build_tree_recursive(X, y, node_indices, branch_name, max_depth, current_depth):
    if max_depth >= current_depth:
        feature_to_split_on  = get_best_split(X, y, node_indices)
        left_indices, right_indices = split_dataset(X, node_indices, feature_to_split_on)
        left_tree  = build_tree_recursive(X, y, left_indices, "Left",max_depth,current_depth+1)
        right_tree = build_tree_recursive(X, y, right_indices, "Right", max_depth, current_depth+1)
        if max_depth == current_depth:
            tree.append(f"Depth {current_depth}, Split on feature: {feature_to_split_on}\nLeft leaf node with indices {left_indices}\nRight leaf node with indices {right_indices}")
        else:
            tree.append(f"Depth {current_depth}, {branch_name} : Split on feature: {feature_to_split_on}")
build_tree_recursive(X_train, y_train, root_indices, "Root", max_depth=1, current_depth=0)
for line in tree:
    print(line)

Depth 1, Split on feature: 0
Left leaf node with indices [0, 1, 4, 7]
Right leaf node with indices [5]
Depth 1, Split on feature: 1
Left leaf node with indices [8]
Right leaf node with indices [2, 3, 6, 9]
Depth 0, Root : Split on feature: 2
